<!DOCTYPE html>
<html>    
    <head>
        <meta charset="utf-8">
        
        <title>TITRE</title>
                
        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="style.css">
    </head>
    
    
    <body>
        <header>
            
            <?php include("header.php"); ?>
            
            <?php include("navbar.php"); ?>

        </header>
    
        <div id="main">
        
            <section id="content">
                <p class="TEMP">
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                    CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE | CORPS DE PAGE |
                </p>
            </section>
            
            <?php include("sidebar.php"); ?> <! Inclure le fichier "sidebar.php" >
       
        </div>
    
    <footer>
        <?php include("footer.php"); ?>
    </footer>
        
    </body>    
</html>
